title: Iron-Kong Web Development
description: Crafting exceptional web solutions tailored to your needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Ironkong.com" # the base hostname & protocol for your site

theme:  jekyll-theme-minimal

# Author
author:
  name: Gift Msebele
  email: msebelegift@gmail.com

# Social Media Links
social:
  twitter: MsebeleJnr
  github: MsebeleJnr
  linkedin: Gift Msebele

# Build settings
markdown: kramdown
highlighter: rouge
