title: My Portfolio Project
description: A portfolio project for a full-stack software engineer showcasing key features and skills.
show_downloads: true
google_analytics: UA-XXXXXXXX-X
theme: jekyll-theme-slate
